server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # Route for the User Service
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**

        # Route for the Account Service
        - id: account-service-route
          uri: lb://account-service
          predicates:
            - Path=/api/v1/accounts/**

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: "${JWT_SECRET_KEY}"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/